version: '2'

services:
  mysql:
    image: mysql:5.7

    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: dantalian

    volumes:
      - ./setup_scripts/database.sql:/docker-entrypoint-initdb.d/database.sql

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: hige
      POSTGRES_USER: hige

  dantalian-rest:
    restart: always
    build: .
    links:
      - mysql

    ports:
      - "8000:8000"
      - "1521:1521"
      - "1630:1630"

    env_file:
      - dantalian.env

    volumes:
      - ./src/bach/data:/images
